In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('spam-hamp.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
df.shape

(5572, 2)

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
vectorizer = CountVectorizer()

In [7]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [8]:
df1 = df.drop(['Category'],axis =1)
df1

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(df1.Message,df1.spam,test_size=0.2)

In [11]:
X_train_count = vectorizer.fit_transform(X_train.values)

In [12]:
#X = df1.Message
#y = df1.spam

In [13]:
#X_count = vectorizer.fit_transform(X.values)

In [14]:
#X_count.shape

In [15]:
#X_train,X_test,y_train,y_test = train_test_split(X_count,y,test_size=0.2)

In [16]:
X_train_count.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

In [18]:
model.fit(X_train_count,y_train)

MultinomialNB()

In [19]:
X_test_count = vectorizer.transform(X_test)

In [20]:
model.score(X_test_count,y_test)

0.9874439461883409

In [28]:
test_email = ['hey brother, are you coming today',
             'This is the 2nd time we have tried 2 contact',
             'this is a 30% special offer for you.']

In [22]:
test_email_count = vectorizer.transform(test_email)
model.predict(test_email_count)

array([0, 1], dtype=int64)

In [23]:
from sklearn.pipeline import Pipeline

In [24]:
clf = Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())])

In [25]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [26]:
clf.score(X_test,y_test)

0.9874439461883409

In [29]:
clf.predict(test_email)

array([0, 1, 0], dtype=int64)